name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          go build -ldflags="-X main.version=$VERSION" -o ./out/iwanc.exe ./src/iwanc/
          go build -ldflags="-X main.version=$VERSION" -o ./out/iwans.exe ./src/iwans/

      - name: CreateRel
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./out/iwans.exe
            ./out/iwanc.exe
          draft: false
          generate_release_notes: true